using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Inv;

namespace Portable
{
	// See http://paletton.com
	public static class ColorPallette
	{

		public static Colour PrimaryColor;
		public static Colour PrimaryColorLight;
		public static Colour PrimaryColorLightAccent;
		public static Colour PrimaryColorDark;
		public static Colour PrimaryColorDarkAccent;

		public static Colour Secondary1Color;
		public static Colour Secondary1ColorLight;
		public static Colour Secondary1ColorLightAccent;
		public static Colour Secondary1ColorDark;
		public static Colour Secondary1ColorDarkAccent;

		public static Colour Secondary2Color;
		public static Colour Secondary2ColorLight;
		public static Colour Secondary2ColorLightAccent;
		public static Colour Secondary2ColorDark;
		public static Colour Secondary2ColorDarkAccent;

		public static Colour ComplementColor;
		public static Colour ComplementColorLight;
		public static Colour ComplementColorLightAccent;
		public static Colour ComplementColorDark;
		public static Colour ComplementColorDarkAccent;


		static ColorPallette()
		{
			var lines = colorMapString.Split('\n');
			List<Colour> colors = new List<Colour>();
			foreach(var line in lines)
			{
				Match colorMatch = rgbRe.Match(line);
				if(colorMatch.Success)
				{
					var r = byte.Parse(colorMatch.Groups["r"].Value);
					var g = byte.Parse(colorMatch.Groups["g"].Value);
					var b = byte.Parse(colorMatch.Groups["b"].Value);
					var color = Colour.FromArgb(byte.MaxValue, r, g, b);
					colors.Add(color);
				}
			}
			PrimaryColor = colors[0];
			PrimaryColorLight = colors[1];
			PrimaryColorLightAccent = colors[2];
			PrimaryColorDark = colors[3];
			PrimaryColorDarkAccent = colors[4];

			Secondary1Color = colors[5];
			Secondary1ColorLight = colors[6];
			Secondary1ColorLightAccent = colors[7];
			Secondary1ColorDark = colors[8];
			Secondary1ColorDarkAccent = colors[9];

			Secondary2Color = colors[10];
			Secondary2ColorLight = colors[11];
			Secondary2ColorLightAccent = colors[12];
			Secondary2ColorDark = colors[13];
			Secondary2ColorDarkAccent = colors[14];

			ComplementColor = colors[15];
			ComplementColorLight = colors[16];
			ComplementColorLightAccent = colors[17];
			ComplementColorDark = colors[18];
			ComplementColorDarkAccent = colors[19];
		}

		static Regex rgbRe = new Regex(@" rgb\((?<r>[ \d]+),(?<g>[ \d]+),(?<b>[ \d]+)\)");





		// I'm too lazy to keep copy-pasting colors. Just read in the whole text map from paletton.
		static string colorMapString = @"
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=72O0u0klVl63+Jtc+t1uFdmQU5s


*** Primary color:

   shade 0 = #30882B = rgb( 48,136, 43) = rgba( 48,136, 43,1) = rgb0(0.188,0.533,0.169)
   shade 1 = #C9E4C8 = rgb(201,228,200) = rgba(201,228,200,1) = rgb0(0.788,0.894,0.784)
   shade 2 = #73BB6F = rgb(115,187,111) = rgba(115,187,111,1) = rgb0(0.451,0.733,0.435)
   shade 3 = #085604 = rgb(  8, 86,  4) = rgba(  8, 86,  4,1) = rgb0(0.031,0.337,0.016)
   shade 4 = #022300 = rgb(  2, 35,  0) = rgba(  2, 35,  0,1) = rgb0(0.008,0.137,0)

*** Secondary color (1):

   shade 0 = #206664 = rgb( 32,102,100) = rgba( 32,102,100,1) = rgb0(0.125,0.4,0.392)
   shade 1 = #AFC8C7 = rgb(175,200,199) = rgba(175,200,199,1) = rgb0(0.686,0.784,0.78)
   shade 2 = #538D8A = rgb( 83,141,138) = rgba( 83,141,138,1) = rgb0(0.325,0.553,0.541)
   shade 3 = #03413E = rgb(  3, 65, 62) = rgba(  3, 65, 62,1) = rgb0(0.012,0.255,0.243)
   shade 4 = #001A19 = rgb(  0, 26, 25) = rgba(  0, 26, 25,1) = rgb0(0,0.102,0.098)

*** Secondary color (2):

   shade 0 = #A86835 = rgb(168,104, 53) = rgba(168,104, 53,1) = rgb0(0.659,0.408,0.208)
   shade 1 = #FFEDDF = rgb(255,237,223) = rgba(255,237,223,1) = rgb0(1,0.929,0.875)
   shade 2 = #E7B389 = rgb(231,179,137) = rgba(231,179,137,1) = rgb0(0.906,0.702,0.537)
   shade 3 = #6A3204 = rgb(106, 50,  4) = rgba(106, 50,  4,1) = rgb0(0.416,0.196,0.016)
   shade 4 = #2B1300 = rgb( 43, 19,  0) = rgba( 43, 19,  0,1) = rgb0(0.169,0.075,0)

*** Complement color:

   shade 0 = #A73537 = rgb(167, 53, 55) = rgba(167, 53, 55,1) = rgb0(0.655,0.208,0.216)
   shade 1 = #FEDEDF = rgb(254,222,223) = rgba(254,222,223,1) = rgb0(0.996,0.871,0.875)
   shade 2 = #E5888B = rgb(229,136,139) = rgba(229,136,139,1) = rgb0(0.898,0.533,0.545)
   shade 3 = #690407 = rgb(105,  4,  7) = rgba(105,  4,  7,1) = rgb0(0.412,0.016,0.027)
   shade 4 = #2B0001 = rgb( 43,  0,  1) = rgba( 43,  0,  1,1) = rgb0(0.169,0,0.004)


#####  Generated by Paletton.com (c) 2002-2014
		";
	}
}